name: Build

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-latest
    env: 
      CI: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn build
