name: spell-check

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  spelling:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: check-spelling/check-spelling@main